import {app, BrowserWindow, ipcMain, dialog} from 'electron';
import {
    createWriteStream,
    existsSync,
    mkdirSync,
    readdirSync,
    readFileSync,
    rm,
    rmdir,
    rmSync,
    writeFileSync
} from "node:fs";
import {basename, join} from "node:path";
import * as toml from "toml";
import {exec, execSync} from "node:child_process";
import {arch, cpus} from "node:os";
import {setInterval} from "node:timers";
import psList from "ps-list";
import {PrepareDeepLinkProtocol} from "./core/deep_links";
import {Mod, ModJSONData, ModWithPriority} from "./types/ui";
import {DMLConfigTOML} from "./types/divamodloader";
import {finished} from "node:stream/promises";
import {Readable, Transform} from "node:stream";
import AdmZip from "adm-zip";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

// only need one instance
const got_app_lock = app.requestSingleInstanceLock();
if (!got_app_lock) app.quit();

let WINDOW!: BrowserWindow;

const createWindow = (): void => {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        width: 1280,
        height: 720,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
        minWidth: 1280,
        minHeight: 720,
    });

    WINDOW = mainWindow;

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
    mainWindow.setMenuBarVisibility(false);

    // Open the DevTools.
    // mainWindow.webContents.openDevTools();

    app.on('second-instance', (event, cli, workingDirectory) => {
        console.log('second-instance event')
        if (mainWindow) {
            if (mainWindow.isMinimized()) mainWindow.restore();
            mainWindow.focus();
        }

        dialog.showErrorBox('Hello deep link', `You arrived from: ${cli.pop()}. If this is working for you, let me know, because I can't get it to work for me!`)
    });

    // This allows updating of the Launch button to be disabled/say "running"
    // just a neat little detail I like
    setInterval(async () => {
        const processes = await psList();
        mainWindow.webContents.send('game-status', {
            status: processes.some(p =>
                p.name.toLowerCase().includes('divamegamix') ||
                p.cmd?.toLowerCase().includes('divamegamix')
            )
        });
    }, 5_000);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
    createWindow();

    // TODO: ADD SETTING FOR THIS FOR WINDOWS USERS
    // on linux since there's no major mod manager for linux
    // I'm going to handle the "divamodmanager:" protocol by default
    if (process.platform == 'linux') PrepareDeepLinkProtocol(app);
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

interface UserConfig {
    game_path: string,
    lang: 'en' | 'es' | 'ja',
    presets: {
        last_used: string,
        configs: Array<{
            name: string,
            mods: Array<{
                path: string,
                enabled: boolean
            }>
        }>
    }
}

let store: UserConfig = {
    game_path: '',
    lang: 'en',
    presets: {
        last_used: 'none',
        configs: []
    }
};

// just try default paths and if they don't work then make the user locate diva

if (existsSync(join(app.getPath('userData'), 'yadmm.conf'))) store = JSON.parse(readFileSync(join(app.getPath('userData'), 'yadmm.conf'), 'utf-8'));
console.log(store);

let MEGAMIX_INSTALL_PATH = store.game_path;

ipcMain.handle('cfg:get-path', () => {
    console.log('handle get path')
    return store.game_path;
});
ipcMain.handle('cfg:set-path', (event, p: string) => {
    console.log('handle store path')
    store.game_path = p;
    MEGAMIX_INSTALL_PATH = p;
    writeFileSync(join(app.getPath('userData'), 'yadmm.conf'), JSON.stringify(store), 'utf-8');
});
ipcMain.handle('cfg:get-lang', async () => {
    console.log('get language')
    return store.lang;
});
ipcMain.handle('cfg:store-lang', (_event, lang) => {
    console.log('store language')
    store.lang = lang;
    writeFileSync(join(app.getPath('userData'), 'yadmm.conf'), JSON.stringify(store), 'utf-8');
});


if (store.game_path == '') {
    switch (process.platform) {
        case 'linux':
            MEGAMIX_INSTALL_PATH = `/home/${process.env.USER}/.steam/steam/steamapps/common/Hatsune Miku Project DIVA Mega Mix Plusa/`;
            break;

        // 99% of players are Windows users
        case 'win32':
        default:
            MEGAMIX_INSTALL_PATH = `C:\\Program Files (x86)\\Steam\\steamapps\\common\\Hatsune Miku Project DIVA Mega Mix Plus`;
            break;
    }
}


ipcMain.handle('cfg:check-game-path', () => {
    console.log('check game path...')
    return existsSync(MEGAMIX_INSTALL_PATH) && existsSync(join(MEGAMIX_INSTALL_PATH, 'DivaMegaMix.exe'));
});

ipcMain.handle('sys:launch-game', async () => {
    console.log('launching game via steam...')
    if (process.platform == 'win32') exec('start steam://rungameid/1761390').once('close', () => {
        return
    });
    if (process.platform == 'linux') exec('xdg-open steam://rungameid/1761390').once('close', () => {
        return
    });
});

ipcMain.handle('fs:get-mod-list', async () => {
    console.log(`getting mod list... (looking for: ${join(MEGAMIX_INSTALL_PATH, 'DivaMegaMix.exe')})`)

    if (!existsSync(MEGAMIX_INSTALL_PATH) || !existsSync(join(MEGAMIX_INSTALL_PATH, 'DivaMegaMix.exe'))) return {
        success: false,
        dml_found: false,
        mods: [],
        error: 'Install path is not valid'
    }

    try {
        if (!existsSync(join(MEGAMIX_INSTALL_PATH, 'mods'))) {
            mkdirSync(join(MEGAMIX_INSTALL_PATH, 'mods'));
            store.game_path = MEGAMIX_INSTALL_PATH;
            writeFileSync(join(app.getPath('userData'), 'yadmm.conf'), JSON.stringify(store), 'utf-8');
            return {
                success: true,
                dml_found: false,
                mods: []
            }
        }

        store.game_path = MEGAMIX_INSTALL_PATH;
        writeFileSync(join(app.getPath('userData'), 'yadmm.conf'), JSON.stringify(store), 'utf-8');
        const entries = readdirSync(join(MEGAMIX_INSTALL_PATH, 'mods'), {withFileTypes: true});
        let i = 0;
        const mods: Array<Mod> = [];

        const dml_found = existsSync(join(MEGAMIX_INSTALL_PATH, 'dinput8.dll'));

        for (const entry of entries) {
            if (entry.isFile()) continue;

            try {
                const mod_meta = toml.parse(readFileSync(join(MEGAMIX_INSTALL_PATH, 'mods', entry.name, 'config.toml'), 'utf-8'));
                const mod_json_path = join(MEGAMIX_INSTALL_PATH, 'mods', entry.name, 'mod.json');
                const fallback_mod_json: ModJSONData = JSON.parse(existsSync(mod_json_path) ? readFileSync(mod_json_path, 'utf-8') : '{}');

                // console.log(mod_meta.name);

                mods.push({
                    enabled: mod_meta.enabled,
                    name: mod_meta.name || fallback_mod_json.name || (entry.name.length > 40 ? entry.name.substring(0, 40) + '...' : entry.name),
                    author: mod_meta.author || fallback_mod_json.submitter,
                    version: mod_meta.version || 'null',
                    id: i,
                    path: join(MEGAMIX_INSTALL_PATH, 'mods', entry.name),
                    mod_json: fallback_mod_json
                    // not used yet, maybe later?
                    // imageUrl: fallback_mod_json.preview || undefined
                });

                i++;
            } catch {
                console.log(`failed to parse ${entry}'s config.toml, skipping!`)
            }
        }

        return {
            success: true,
            dml_found,
            mods: mods,
        }
    } catch (error) {
        return {
            success: false,
            dml_found: false,
            mods: [],
            error: error instanceof Error ? error.message : 'Failed to read mods, unknown reason.'
        }
    }
})

ipcMain.handle('fs:get-mod-list-priorities', async () => {
    console.log(`getting mod list... (looking for: ${join(MEGAMIX_INSTALL_PATH, 'DivaMegaMix.exe')})`)

    if (!existsSync(MEGAMIX_INSTALL_PATH) || !existsSync(join(MEGAMIX_INSTALL_PATH, 'DivaMegaMix.exe'))) return {
        success: false,
        dml_found: false,
        mods: [],
        error: 'Install path is not valid'
    }

    try {
        if (!existsSync(join(MEGAMIX_INSTALL_PATH, 'mods'))) {
            mkdirSync(join(MEGAMIX_INSTALL_PATH, 'mods'));
            store.game_path = MEGAMIX_INSTALL_PATH;
            writeFileSync(join(app.getPath('userData'), 'yadmm.conf'), JSON.stringify(store), 'utf-8');
            return {
                success: true,
                dml_found: false,
                mods: []
            }
        }

        store.game_path = MEGAMIX_INSTALL_PATH;
        writeFileSync(join(app.getPath('userData'), 'yadmm.conf'), JSON.stringify(store), 'utf-8');
        const entries = readdirSync(join(MEGAMIX_INSTALL_PATH, 'mods'), {withFileTypes: true});
        let i = 0;
        const mods: Array<ModWithPriority> = [];

        const dml_config: DMLConfigTOML = toml.parse(readFileSync(join(MEGAMIX_INSTALL_PATH, 'config.toml'), 'utf-8'));

        const dml_found = existsSync(join(MEGAMIX_INSTALL_PATH, 'dinput8.dll'));

        for (const entry of entries) {
            if (entry.isFile()) continue;

            try {
                const mod_meta = toml.parse(readFileSync(join(MEGAMIX_INSTALL_PATH, 'mods', entry.name, 'config.toml'), 'utf-8'));
                const mod_json_path = join(MEGAMIX_INSTALL_PATH, 'mods', entry.name, 'mod.json');
                const fallback_mod_json: ModJSONData = JSON.parse(existsSync(mod_json_path) ? readFileSync(mod_json_path, 'utf-8') : '{}');

                // console.log(mod_meta.name);
                if (!mod_meta.enabled) continue;

                mods.push({
                    enabled: true,
                    name: mod_meta.name || fallback_mod_json.name || (entry.name.length > 40 ? entry.name.substring(0, 40) + '...' : entry.name),
                    author: mod_meta.author || fallback_mod_json.submitter,
                    version: mod_meta.version || 'null',
                    id: i,
                    path: join(MEGAMIX_INSTALL_PATH, 'mods', entry.name),
                    priority: dml_config.priority.indexOf(entry.name) || -1,
                    mod_json: fallback_mod_json
                    // not used yet, maybe later?
                    // imageUrl: fallback_mod_json.preview || undefined
                });

                i++;
            } catch {
                console.log(`failed to parse ${entry}'s config.toml, skipping!`)
            }
        }

        return {
            success: true,
            dml_found,
            mods: mods.sort((a, b) => {
                return a.priority - b.priority;
            }).map(mod => {
                mod.priority = mods.indexOf(mod);
                return mod;
            }),
        }
    } catch (error) {
        return {
            success: false,
            dml_found: false,
            mods: [],
            error: error instanceof Error ? error.message : 'Failed to read mods, unknown reason.'
        }
    }
})

ipcMain.handle('fs:save-mod-priorities', async (_event, priorities: Array<ModWithPriority>) => {
    // read DivaModLoader's config.toml
    const config_toml: DMLConfigTOML = toml.parse(readFileSync(join(MEGAMIX_INSTALL_PATH, 'config.toml'), 'utf-8'));
    config_toml.priority = []; // reset priorities
    for (const mod of priorities.sort((a, b) => a.priority - b.priority)) {
        // priority list uses the folder name of the mods
        const mod_folder_name = basename(mod.path);
        config_toml.priority.push(mod_folder_name);
    }
    // use the same method of saving enable/disable toggle for saving this line of config
    const raw_toml_lines = readFileSync(join(MEGAMIX_INSTALL_PATH, 'config.toml'), 'utf-8').split('\n');
    raw_toml_lines[raw_toml_lines.indexOf(raw_toml_lines.find(line => line.startsWith('priority')))]
        = `priority = [${config_toml.priority.map(p => `"${p}"`).join(', ')}]`;

    writeFileSync(join(MEGAMIX_INSTALL_PATH, 'config.toml'), raw_toml_lines.join('\n'));
});


ipcMain.handle('fs:toggle-mod', async (_event, mod_path: string, enabled: boolean) => {
    if (!existsSync(mod_path)) return;

    const config_toml_data = readFileSync(join(mod_path, 'config.toml'), 'utf-8');
    const lines = config_toml_data.split('\n');
    const line_index = lines.indexOf(lines.find((line) => line.startsWith('enabled')));
    lines[line_index] = `enabled = ${enabled}`;

    writeFileSync(join(mod_path, 'config.toml'), lines.join('\n'), 'utf-8');
});

ipcMain.handle('fs:uninstall-mod', async (_event, mod_path: string) => {
    console.log(`uninstalling mod: ${mod_path}`)
    if (!existsSync(mod_path)) return false;
    if (!mod_path.includes(MEGAMIX_INSTALL_PATH)) return false;
    if (!existsSync(join(mod_path, 'config.toml'))) return false;
    try {
        rmSync(mod_path, {recursive: true, maxRetries: 5});
        console.log(`deleted directory: ${mod_path}`);
        return true;
    } catch (err) {
        console.error(err);
        return false;
    }
});

ipcMain.handle('fs:update-mod', async (_event, mod_path: string) => {
    if (!mod_path.includes(MEGAMIX_INSTALL_PATH)) return false;

    const mod_json: ModJSONData = JSON.parse(readFileSync(join(mod_path, 'mod.json'), 'utf-8'));
    if (!mod_json.homepage.includes('divamodarchive')) return false;

    if (!existsSync(join(MEGAMIX_INSTALL_PATH, '.yadmm-cache'))) mkdirSync(join(MEGAMIX_INSTALL_PATH, '.yadmm-cache'));
    if (existsSync(join(MEGAMIX_INSTALL_PATH, '.yadmm-cache', `mod-${mod_json.id}.zip`))) rmSync(join(MEGAMIX_INSTALL_PATH, '.yadmm-cache', `mod-${mod_json.id}.zip`));

    console.log('starting mod download...');
    const response = await fetch(`https://divamodarchive.com/api/v1/posts/${mod_json.id}/download/0`);
    if (!response.ok) return false;

    const totalBytes = Number(response.headers.get('content-length')) || 0;
    let downloadedBytes = 0;
    let lastPercent = -1;

    const fileStream = createWriteStream(join(MEGAMIX_INSTALL_PATH, '.yadmm-cache', `mod-${mod_json.id}.zip`));

    const progressStream = new Transform({
        transform(chunk, _encoding, callback) {
            downloadedBytes += chunk.length;

            if (totalBytes > 0) {
                const percent = Math.floor((downloadedBytes / totalBytes) * 100);

                if (percent !== lastPercent) {
                    lastPercent = percent;
                    console.log(`download progress: ${percent}%`);

                    WINDOW.webContents.send('download-progress', {
                        percent,
                        downloadedBytes,
                        totalBytes,
                        status: 'downloading'
                    });
                }
            } else {
                console.log(`downloaded ${downloadedBytes} bytes`);
            }

            callback(null, chunk);
        }
    });

    await finished(
        Readable.fromWeb(response.body as never)
            .pipe(progressStream)
            .pipe(fileStream)
    );

    console.log('download finished!');

    WINDOW.webContents.send('download-progress', {
        percent: 100,
        downloadedBytes,
        totalBytes,
        status: 'installing'
    });

    const zip = new AdmZip(join(MEGAMIX_INSTALL_PATH, '.yadmm-cache', `mod-${mod_json.id}.zip`));
    zip.extractAllTo(mod_path, true);

    WINDOW.webContents.send('download-progress', {percent: 100, downloadedBytes, totalBytes, status: 'finished'});

    return true;
});

ipcMain.handle('other:debugstr', () => {
    if (process.platform == 'win32') {
        return `yadmm ${app.getVersion()} on Win32 ${arch()} ${cpus()[0].model} `;
    }
    if (process.platform == 'linux') {
        return `yadmm ${app.getVersion()} on ${execSync('uname -snrm')} ${cpus()[0].model}`;
    }
});

ipcMain.handle('other:kofi', () => {
    if (process.platform == 'win32') return exec('start "https://ko-fi.com/okawaffles"');
    if (process.platform == 'linux') return exec('xdg-open "https://ko-fi.com/okawaffles"');
});