import {app, BrowserWindow, ipcMain} from 'electron';
import {existsSync, mkdirSync, readdirSync, readFileSync} from "node:fs";
import {join} from "node:path";
import * as toml from "toml";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

const createWindow = (): void => {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        width: 1280,
        height: 720,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
        minWidth: 1280,
        minHeight: 720,
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
    mainWindow.setMenuBarVisibility(false);

    // Open the DevTools.
    // mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

const MEGAMIX_INSTALL_PATH = '/home/millie/.local/share/Steam/steamapps/common/Hatsune Miku Project DIVA Mega Mix Plus/'

ipcMain.handle('fs:get-mod-list', async () => {
    try {
        if (!existsSync(join(MEGAMIX_INSTALL_PATH, 'mods'))) {
            mkdirSync(join(MEGAMIX_INSTALL_PATH, 'mods'));
            return {
                success: true,
                mods: []
            }
        }

        const entries = readdirSync(join(MEGAMIX_INSTALL_PATH, 'mods'), {withFileTypes: true});
        let i = 0;
        const mods: Array<{name: string, author: string, enabled: boolean, id: number, version: string}> = [];

        for (const entry of entries) {
            if (entry.isFile()) continue;

            try {
                const mod_meta = toml.parse(readFileSync(join(MEGAMIX_INSTALL_PATH, 'mods', entry.name, 'config.toml'), 'utf-8'));
                    const mod_json_path = join(MEGAMIX_INSTALL_PATH, 'mods', entry.name, 'mod.json');
                const fallback_mod_json = JSON.parse(existsSync(mod_json_path) ? readFileSync(mod_json_path, 'utf-8') : '{}');

                mods.push({
                    enabled: mod_meta.enabled,
                    name: mod_meta.name || fallback_mod_json.name || (entry.name.length > 40 ? entry.name.substring(0, 40) + '...' : entry.name),
                    author: mod_meta.author || fallback_mod_json.submitter,
                    version: mod_meta.version || 'No Version Specified',
                    id: i
                });

                i++;
            } catch {
                console.log(`failed to parse ${entry}'s config.toml, skipping!`)
            }
        }

        return {
            success: true,
            mods: mods,
        }
    } catch (error) {
        return {
            success: false,
            mods: [],
            error: error instanceof Error ? error.message : 'Failed to read mods, unknown reason.'
        }
    }
})