import {app, BrowserWindow, ipcMain} from 'electron';
import {existsSync, mkdirSync, readdirSync, readFileSync, rm, rmdir, rmSync, writeFileSync} from "node:fs";
import {join} from "node:path";
import * as toml from "toml";
import {exec, execSync} from "node:child_process";
import {arch, cpus} from "node:os";
import {setInterval} from "node:timers";
import psList from "ps-list";
// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
    app.quit();
}

const createWindow = (): void => {
    // Create the browser window.
    const mainWindow = new BrowserWindow({
        width: 1280,
        height: 720,
        webPreferences: {
            preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
        },
        minWidth: 1280,
        minHeight: 720,
    });

    // and load the index.html of the app.
    mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
    mainWindow.setMenuBarVisibility(false);

    // Open the DevTools.
    // mainWindow.webContents.openDevTools();


    // This allows updating of the Launch button to be disabled/say "running"
    // just a neat little detail I like
    setInterval(async () => {
        const processes = await psList();
        mainWindow.webContents.send('game-status', {
            status: processes.some(p =>
                p.name.toLowerCase().includes('divamegamix') ||
                p.cmd?.toLowerCase().includes('divamegamix')
            )
        });
    }, 5_000);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
    if (process.platform !== 'darwin') {
        app.quit();
    }
});

app.on('activate', () => {
    // On OS X it's common to re-create a window in the app when the
    // dock icon is clicked and there are no other windows open.
    if (BrowserWindow.getAllWindows().length === 0) {
        createWindow();
    }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

interface UserConfig {
    game_path: string,
    lang: 'en' | 'es' | 'ja',
    presets: {
        last_used: string,
        configs: Array<{
            name: string,
            mods: Array<{
                path: string,
                enabled: boolean
            }>
        }>
    }
}

let store: UserConfig = {
    game_path: '',
    lang: 'en',
    presets: {
        last_used: 'none',
        configs: []
    }
};

// just try default paths and if they dont work then make the user locate diva

if (existsSync(join(app.getPath('userData'), 'yadmm.conf'))) store = JSON.parse(readFileSync(join(app.getPath('userData'), 'yadmm.conf'), 'utf-8'));
console.log(store);

let MEGAMIX_INSTALL_PATH = store.game_path;

ipcMain.handle('cfg:get-path', () => {
    console.log('handle get path')
    return store.game_path;
});
ipcMain.handle('cfg:set-path', (event, p: string) => {
    console.log('handle store path')
    store.game_path = p;
    MEGAMIX_INSTALL_PATH = p;
    writeFileSync(join(app.getPath('userData'), 'yadmm.conf'), JSON.stringify(store), 'utf-8');
});


if (store.game_path == '') {
    switch (process.platform) {
        case 'linux':
            MEGAMIX_INSTALL_PATH = `/home/${process.env.USER}/.steam/steam/steamapps/common/Hatsune Miku Project DIVA Mega Mix Plusa/`;
            break;

        // 99% of players are windows users
        case 'win32':
        default:
            MEGAMIX_INSTALL_PATH = `C:\\Program Files (x86)\\Steam\\steamapps\\common\\Hatsune Miku Project DIVA Mega Mix Plus`;
            break;
    }
}


ipcMain.handle('cfg:check-game-path', () => {
    console.log('check game path...')
    return existsSync(MEGAMIX_INSTALL_PATH) && existsSync(join(MEGAMIX_INSTALL_PATH, 'DivaMegaMix.exe'));
});

ipcMain.handle('sys:launch-game', async () => {
    console.log('launching game via steam...')
    if (process.platform == 'win32') exec('start steam://rungameid/1761390').once('close', () => {return});
    if (process.platform == 'linux') exec('xdg-open steam://rungameid/1761390').once('close', () => {return});
});

ipcMain.handle('fs:get-mod-list', async () => {
    console.log(`getting mod list... (looking for: ${join(MEGAMIX_INSTALL_PATH, 'DivaMegaMix.exe')})`)

    if (!existsSync(MEGAMIX_INSTALL_PATH) || !existsSync(join(MEGAMIX_INSTALL_PATH, 'DivaMegaMix.exe'))) return {
        success: false,
        dml_found: false,
        mods: [],
        error: 'Install path is not valid'
    }

    try {
        if (!existsSync(join(MEGAMIX_INSTALL_PATH, 'mods'))) {
            mkdirSync(join(MEGAMIX_INSTALL_PATH, 'mods'));
            store.game_path = MEGAMIX_INSTALL_PATH;
            writeFileSync(join(app.getPath('userData'), 'yadmm.conf'), JSON.stringify(store), 'utf-8');
            return {
                success: true,
                dml_found: false,
                mods: []
            }
        }

        store.game_path = MEGAMIX_INSTALL_PATH;
        writeFileSync(join(app.getPath('userData'), 'yadmm.conf'), JSON.stringify(store), 'utf-8');
        const entries = readdirSync(join(MEGAMIX_INSTALL_PATH, 'mods'), {withFileTypes: true});
        let i = 0;
        const mods: Array<{name: string, author: string, enabled: boolean, id: number, version: string, imageUrl?: string, path: string}> = [];

        const dml_found = existsSync(join(MEGAMIX_INSTALL_PATH, 'dinput8.dll'));

        for (const entry of entries) {
            if (entry.isFile()) continue;

            try {
                const mod_meta = toml.parse(readFileSync(join(MEGAMIX_INSTALL_PATH, 'mods', entry.name, 'config.toml'), 'utf-8'));
                const mod_json_path = join(MEGAMIX_INSTALL_PATH, 'mods', entry.name, 'mod.json');
                const fallback_mod_json = JSON.parse(existsSync(mod_json_path) ? readFileSync(mod_json_path, 'utf-8') : '{}');

                // console.log(mod_meta.name);

                mods.push({
                    enabled: mod_meta.enabled,
                    name: mod_meta.name || fallback_mod_json.name || (entry.name.length > 40 ? entry.name.substring(0, 40) + '...' : entry.name),
                    author: mod_meta.author || fallback_mod_json.submitter,
                    version: mod_meta.version || 'No Version Specified',
                    id: i,
                    path: join(MEGAMIX_INSTALL_PATH, 'mods', entry.name),
                    // not used yet, maybe later?
                    // imageUrl: fallback_mod_json.preview || undefined
                });

                i++;
            } catch {
                console.log(`failed to parse ${entry}'s config.toml, skipping!`)
            }
        }

        return {
            success: true,
            dml_found,
            mods: mods,
        }
    } catch (error) {
        return {
            success: false,
            dml_found: false,
            mods: [],
            error: error instanceof Error ? error.message : 'Failed to read mods, unknown reason.'
        }
    }
})

ipcMain.handle('fs:toggle-mod', async (_event, mod_path: string, enabled: boolean) => {
    if (!existsSync(mod_path)) return;

    const config_toml_data = readFileSync(join(mod_path, 'config.toml'), 'utf-8');
    const lines = config_toml_data.split('\n');
    const line_index = lines.indexOf(lines.find((line) => line.startsWith('enabled')));
    lines[line_index] = `enabled = ${enabled}`;

    writeFileSync(join(mod_path, 'config.toml'), lines.join('\n'), 'utf-8');
});

ipcMain.handle('fs:uninstall-mod', async (_event, mod_path: string) => {
    console.log(`uninstalling mod: ${mod_path}`)
    if (!existsSync(mod_path)) return false;
    if (!mod_path.includes(MEGAMIX_INSTALL_PATH)) return false;
    if (!existsSync(join(mod_path, 'config.toml'))) return false;
    try {
        rmSync(mod_path, {recursive: true, maxRetries: 5});
        console.log(`deleted directory: ${mod_path}`);
        return true;
    } catch (err) {
        console.error(err);
        return false;
    }
});

ipcMain.handle('other:debugstr', () => {
    if (process.platform == 'win32') {
        return `yadmm ${app.getVersion()} on Win32 ${arch()} ${cpus()[0].model} `;
    }
    if (process.platform == 'linux') {
        return `yadmm ${app.getVersion()} on ${execSync('uname -snrm')} ${cpus()[0].model}`;
    }
});

ipcMain.handle('other:kofi', () => {
    if (process.platform == 'win32') return exec('start "https://ko-fi.com/okawaffles"');
    if (process.platform == 'linux') return exec('xdg-open "https://ko-fi.com/okawaffles"');
});